title:               Hansol Shin | 신한솔
url:                 https://hansol-s.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Hansol Shin
  url:               hansol-s.github.io
  email:

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
